# Generated by Django 5.2.6 on 2025-09-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_profile_favorite_game_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
