# Generated by Django 5.2.6 on 2025-10-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_facebook_profile_linkedin_profile_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkedin',
            new_name='twitch',
        ),
    ]
