# Generated by Django 5.2.6 on 2025-10-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_linkedin_profile_twitch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twitch',
            new_name='youtube',
        ),
    ]
