# Generated by Django 5.2.6 on 2025-10-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_twitch_profile_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='youtube',
            new_name='instgram',
        ),
    ]
