# Generated by Django 5.2.6 on 2025-10-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_youtube_profile_instgram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instgram',
            new_name='instagram',
        ),
    ]
