# Generated by Django 5.2.6 on 2025-10-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_instgram_profile_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='linkedin',
        ),
    ]
